version: "3.9"

services:

  kafka-0:
    image: ${KAFKA_IMAGE}
    ports:
      - "9094:9094"
    env_file: .env
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka-0:9092,CLIENT://127.0.0.1:9094
    volumes:
      - ./client.properties:/tmp/client.properties:ro
      - ./kafka0/kafka0.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./src/main/resources/ssl/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

  kafka-1:
    image: ${KAFKA_IMAGE}
    ports:
      - "9095:9094"
    env_file: .env
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka-1:9092,CLIENT://127.0.0.1:9095
    volumes:
      - ./kafka1/kafka1.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./src/main/resources/ssl/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

  kafka-2:
    image: ${KAFKA_IMAGE}
    ports:
      - "9096:9094"
    env_file: .env
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://kafka-2:9092,CLIENT://127.0.0.1:9096
    volumes:
      - ./kafka2/kafka2.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
      - ./src/main/resources/ssl/kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

  ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kraft
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka-0:9092,kafka-0:9092,kafka-0:9092
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="ui_user" password="ui_password";