
spring:

  # благодаря зависимости spring-kafka, можно задавать настройки kafka и kafka streams в yaml
  kafka:
    bootstrap-servers: localhost:9094, localhost:9095, localhost:9096

    # но настройки для kafka streams и kafka задаются в разных блоках
    # в блоке spring.kafka.streams для kafka streams
    streams:
      application-id:  app
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde


    # В блоке spring.kafka.producer/consumer - настройки producer/consumer для kafka
    # так как я все еще использую producer из kafka, поэтому задаю настройки и ему
    # вообще все настройки лучше задавать в коде, потому что там есть константы. Тут задал для демонстрации
    producer:
      properties:
        enable.idempotence: true
        min.insync.replicas: 2
        retries: 3
        acks: all

    consumer:
      group-id: id


    topic:
      # команды блокировки пользователей
      user-blocking-commands: user-blocking-commands

      # отправленные сообщения
      sent-messages: sent-messages

      # доставленные сообщения
      delivered-messages: delivered-messages

      # заблокированные сообщения
      blocked-messages: blocked-messages

      # запрещенные слова
      bad-words: bad-words




# ниже не смотрим, это просто для удобства

springdoc:
  swagger-ui:
    path: /

logging:
  pattern:
    console: "%d{dd.MM HH:mm:ss:SSS, Europe/Moscow} %highlight(%-5level) %cyan(%35.35(%logger{0}) %blue(%-20.20M)) %msg %n"